# Path related
raw_dataset_path: data/raw/machining_maintenance.csv
dataset_path: data/output/data.pkl
input_set_path: data/output/input.pkl
output_set_path: data/output/output.pkl
input_cols_path: data/output/input_cols.pkl
train_set_path:
- data/output/X_train.pkl
- data/output/y_train.pkl
valid_set_path:
- data/output/X_valid.pkl
- data/output/y_valid.pkl
test_set_path:
- data/output/X_test.pkl
- data/output/y_test.pkl

# Preprocessing related
output_cols: 'Failure Type'
drop_cols: 
- 'Product ID'
- 'Failure Type'
seed: 123
test_size: 0.2
num_cols:
- 'Air temperature [K]' 
- 'Process temperature [K]'
- 'Rotational speed [rpm]' 
- 'Torque [Nm]'
- 'Tool wear [min]'
cat_cols:
- 'Type'
num_imputer_path : data/output/num_imputer.pkl
cat_imputer_path : data/output/cat_imputer.pkl
scaler_path : data/output/scaler.pkl
train_clean_path : data/output/X_train_clean.pkl
valid_clean_path : data/output/X_valid_clean.pkl
test_clean_path : data/output/X_test_clean.pkl


# Modeling related
list_of_model_path: log/list_of_model.pkl
list_of_param_path: log/list_of_param.pkl
list_of_tuned_model_path: log/list_of_tuned_model.pkl
best_model_path: models/best_model.pkl
best_threshold_path: models/best_threshold.pkl